export declare const stylePropTypeMapping: {
    readonly display: "block | inline | inline-block | flex | grid | none | contents | table | table-row | table-cell | table-column | table-column-group | table-footer-group | table-header-group | table-row-group | table-caption | list-item | run-in";
    readonly width: "number | string";
    readonly minWidth: "number | string";
    readonly maxWidth: "number | string";
    readonly height: "number | string";
    readonly minHeight: "number | string";
    readonly maxHeight: "number | string";
    readonly padding: "number | string";
    readonly paddingTop: "number | string";
    readonly paddingRight: "number | string";
    readonly paddingBottom: "number | string";
    readonly paddingLeft: "number | string";
    readonly margin: "number | string";
    readonly marginTop: "number | string";
    readonly marginRight: "number | string";
    readonly marginBottom: "number | string";
    readonly marginLeft: "number | string";
    readonly flexDirection: "row | row-reverse | column | column-reverse";
    readonly flexWrap: "nowrap | wrap | wrap-reverse";
    readonly justifyContent: "flex-start | flex-end | center | space-between | space-around | space-evenly";
    readonly alignItems: "flex-start | flex-end | center | baseline | stretch";
    readonly alignContent: "flex-start | flex-end | center | space-between | space-around | stretch";
    readonly flexBasis: "number | string";
    readonly flexGrow: "number";
    readonly flexShrink: "number";
    readonly flex: "number | string";
    readonly alignSelf: "auto | flex-start | flex-end | center | baseline | stretch";
    readonly position: "static | relative | absolute | fixed | sticky";
    readonly top: "number | string";
    readonly right: "number | string";
    readonly bottom: "number | string";
    readonly left: "number | string";
    readonly zIndex: "number";
    readonly overflow: "visible | hidden | scroll | auto";
    readonly overflowX: "visible | hidden | scroll | auto";
    readonly overflowY: "visible | hidden | scroll | auto";
    readonly visibility: "visible | hidden | collapse";
    readonly backgroundColor: "string";
    readonly color: "string";
    readonly border: "string";
    readonly borderRadius: "number | string";
    readonly boxShadow: "string";
    readonly opacity: "number";
    readonly cursor: "auto | default | pointer | wait | text | move | not-allowed | crosshair | progress | alias | cell | copy | grab | grabbing | help | zoom-in | zoom-out";
    readonly transition: "string";
    readonly transform: "string";
    readonly animation: "string";
    readonly fontSize: "number | string";
    readonly fontWeight: "normal | bold | bolder | lighter | number | inherit | initial | unset";
    readonly lineHeight: "number | string";
    readonly letterSpacing: "number | string";
    readonly textAlign: "left | right | center | justify | start | end | match-parent | justify-all | start | end";
    readonly textDecoration: "none | underline | overline | line-through | blink | inherit | initial | unset";
    readonly textTransform: "none | capitalize | uppercase | lowercase | full-width | inherit | initial | unset";
    readonly whiteSpace: "normal | nowrap | pre | pre-line | pre-wrap | break-spaces";
    readonly wordBreak: "normal | break-all | keep-all | break-word";
    readonly wordWrap: "normal | break-word | inherit | initial | unset";
    readonly clipPath: "string";
    readonly gap: "string | number";
    readonly background: "string";
    readonly gridTemplateColumns: "string";
    readonly gridTemplateRows: "string";
    readonly gridTemplateAreas: "string";
    readonly gridAutoFlow: "row | column | row-dense | column-dense";
    readonly gridAutoColumns: "string";
    readonly gridAutoRows: "string";
    readonly pointerEvents: "none | auto | all | inherit | initial | unset";
    readonly mask: "string";
    readonly maskImage: "string";
    readonly maskPosition: "string";
    readonly filter: "string";
    readonly aspectRatio: "number | string";
    readonly transformOrigin: "string";
    readonly userSelect: "none | text | all | inherit | initial | unset";
    readonly rowGap: "string | number";
    readonly columnGap: "string | number";
    readonly boxSizing: "content-box | border-box | inherit | initial | unset";
};
export default stylePropTypeMapping;
